# Generated by Django 5.0.2 on 2024-02-26 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_course_featured_img_course_techs_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='featured_img',
        ),
        migrations.RemoveField(
            model_name='course',
            name='techs',
        ),
        migrations.AddField(
            model_name='coursecategory',
            name='featured_img',
            field=models.ImageField(null=True, upload_to='course_imgs/'),
        ),
        migrations.AddField(
            model_name='coursecategory',
            name='techs',
            field=models.TextField(null=True),
        ),
    ]
