# Generated by Django 5.0.2 on 2024-03-01 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_course_featured_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='featured_img',
            field=models.ImageField(null=True, upload_to='course_imgs/'),
        ),
    ]
